import { describe, expect, it } from "vitest";
import {
  toCommitments,
  toPlayerLike,
  type FixtureRsvpView,
  type PlayerRow,
} from "./mappers";

/**
 * The boundary between nullable database rows and the domain, which has no nulls.
 *
 * Pure, so this runs in the normal suite. It is also the only part of lib/repo that
 * the port does not rewrite — but the types it maps from are generated by Supabase
 * today and inferred by Drizzle after N10, so what it accepts is worth pinning.
 */

const row: PlayerRow = {
  id: "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
  telegram_user_id: 12345,
  telegram_username: "leo",
  is_guest: false,
  invited_by: null,
  first_name: "Leo",
  last_name: null,
  display_name: "Leo",
  emoji: "🦁",
  is_active: true,
  private_chat_id: null,
  created_at: "2026-08-01T00:00:00Z",
  updated_at: "2026-08-01T00:00:00Z",
  rating: 72.5,
};

function rsvp(overrides: Partial<FixtureRsvpView>): FixtureRsvpView {
  return {
    fixture_id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    player_id: row.id,
    display_name: "Leo",
    emoji: "🦁",
    rating: 72.5,
    status: "in",
    in_since: "2026-09-08T12:00:00Z",
    responded_at: "2026-09-08T12:00:00Z",
    promoted_at: null,
    squad_position: 1,
    is_waitlisted: false,
    ...overrides,
  } as FixtureRsvpView;
}

describe("toPlayerLike", () => {
  it("narrows a row to what the domain needs", () => {
    expect(toPlayerLike(row)).toEqual({
      id: row.id,
      displayName: "Leo",
      emoji: "🦁",
      rating: 72.5,
    });
  });

  it("coerces a numeric rating that arrives as a string", () => {
    // Postgres numeric comes back as a string over the wire, and the balancer does
    // arithmetic on it. "72.50" + 5 is a bug that only shows up in the team sheet.
    const asString = { ...row, rating: "72.50" as unknown as number };
    expect(toPlayerLike(asString).rating).toBe(72.5);
  });
});

describe("toCommitments", () => {
  it("keeps players who are in", () => {
    const commitments = toCommitments([rsvp({})]);

    expect(commitments).toHaveLength(1);
    expect(commitments[0]!.player.displayName).toBe("Leo");
    expect(commitments[0]!.inSince).toEqual(new Date("2026-09-08T12:00:00Z"));
  });

  it("drops anybody who is out or undecided", () => {
    expect(
      toCommitments([rsvp({ status: "out" }), rsvp({ status: "maybe" })]),
    ).toEqual([]);
  });

  it("drops an in row with no in_since rather than defaulting it", () => {
    // Defaulting to the epoch would silently put them first in the queue for a game
    // they may not even have answered for — a missing stamp is a bug, not a player.
    expect(toCommitments([rsvp({ in_since: null })])).toEqual([]);
  });

  it("drops a row with no player", () => {
    expect(toCommitments([rsvp({ player_id: null })])).toEqual([]);
  });

  it("falls back for a missing emoji and rating", () => {
    const [commitment] = toCommitments([rsvp({ emoji: null, rating: null })]);

    expect(commitment!.player.emoji).toBe("⚽");
    expect(commitment!.player.rating).toBe(65);
  });

  it("preserves the order it is given, which is the waitlist order", () => {
    const first = rsvp({
      display_name: "First",
      in_since: "2026-09-08T10:00:00Z",
    });
    const second = rsvp({
      display_name: "Second",
      in_since: "2026-09-08T11:00:00Z",
    });

    expect(
      toCommitments([first, second]).map((c) => c.player.displayName),
    ).toEqual(["First", "Second"]);
  });
});
